# Generated by Django 5.2.8 on 2025-11-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='cast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='imdb_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='poster_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
